
# # MySQL Configuration
# host = "mysql"         # MySQL host (default is 127.0.0.1)
# user = "root"              # MySQL user (default is root)
# pass = "helloload"                  # MySQL user password (default is empty)
# db = "subscan"             # MySQL database name (default is "subscan")

[conf]
    host = "mysql"
    user = "root"
    pass = "helloload"
    db   = "subscan"
[api]
    dsn = "?readTimeout=2s&writeTimeout=3s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
[task]
    dsn = "?parseTime=true&loc=Local&charset=utf8mb4,utf8"
[test]
    dsn = "root:@tcp(mysql)/subscan?parseTime=true&loc=Local&charset=utf8mb4,utf8"


